// Bilingual content for portfolio
// All content is original / translated from the user's GitHub repo.

window.DATA = {
  pt: {
    locale: 'pt-BR',
    meta: {
      handle: 'vzanonato',
      host: 'portfolio',
      name1: 'Carlos Vinicius',
      name2: 'Garcia Zanonato',
      role: ['Sistemas de Informação', 'Pesquisador', 'IA & Biociências'],
      location: 'Restinga Sêca, RS · Brasil',
      status: 'Disponível',
      timezone: 'BRT (UTC−3)',
    },
    nav: {
      home: 'início',
      about: 'sobre',
      stack: 'stack',
      experience: 'experiência',
      education: 'formação',
      projects: 'projetos',
      courses: 'cursos',
      contact: 'contato',
    },
    hero: {
      cmd: 'whoami',
      cmdOut: 'retornou 1 resultado em 0.003s',
      greeting: 'Sou',
      intro: 'Estudante de Sistemas de Informação, pesquisador por natureza e apaixonado por tecnologia, biociências e Inteligência Artificial. Este espaço documenta minha trajetória — experiências de pesquisa, projetos pessoais e formação contínua.',
      metaLabels: { based: 'baseado em', tz: 'fuso', focus: 'foco', langs: 'idiomas' },
      focus: 'IA · Virologia · Engenharia Genética',
      langs: 'PT · EN (intermediário)',
      cta1: 'iniciar conversa',
      cta2: 'ver sobre.md',
      portraitTag: 'fotocurriculo.png',
    },
    about: {
      cmd: '$ cat ~/sobre.md',
      panelLeftFile: 'perfil.json',
      panelRightFile: 'resumo.md',
      bio: [
        'Acadêmico de Sistemas de Informação com 3 anos de experiência em pesquisa científica e laboratório biológico na Unipampa. Tenho grande interesse em Virologia, Engenharia Genética e Microbiologia — áreas que aprofundei com cursos complementares.',
        'Busco integrar tecnologia e ciências biológicas para criar soluções inovadoras. Atualmente concilio a formação em SI com a paixão por pesquisa e Inteligência Artificial. Inglês intermediário, boa comunicação, e motivação por novos desafios.',
      ],
      kv: [
        ['nome', 'Carlos Vinicius Garcia Zanonato'],
        ['localização', 'Restinga Sêca, RS, Brasil'],
        ['email', { type: 'mail', value: 'viniciuszanona@gmail.com' }],
        ['linkedin', { type: 'ext', value: 'carlos-vinicius-garcia-zanonato', href: 'https://www.linkedin.com/in/carlos-vinicius-garcia-zanonato-453832346' }],
        ['github', { type: 'ext', value: '@ViniciusZanonato', href: 'https://github.com/ViniciusZanonato' }],
        ['idiomas', 'Português (nativo) · Inglês (intermediário)'],
        ['mei / cnpj', '66.683.588/0001-33'],
      ],
      compHead: 'competências',
      comps: [
        { v: '3y', l: 'em pesquisa' },
        { v: '5+', l: 'projetos' },
        { v: '11', l: 'certificações' },
        { v: '∞', l: 'curiosidade' },
      ],
    },
    stack: {
      cmd: '$ ls ~/.interests/',
      groupsTitle: 'áreas de interesse',
      groups: [
        { title: 'tecnologia', items: ['Python', 'JavaScript', 'HTML/CSS', 'IA & LLMs', 'Bioinformática', 'Pipefy', 'Git'] },
        { title: 'biociências', items: ['Virologia', 'Engenharia Genética', 'Microbiologia', 'CRISPR', 'Biologia molecular'] },
        { title: 'soft skills', items: ['Pesquisa', 'Pensamento analítico', 'Comunicação', 'Aprendizado rápido', 'Inglês'] },
      ],
    },
    experience: {
      cmd: '$ git log --oneline experience/',
      title: 'experiência profissional',
      items: [
        {
          hash: 'mar 2025',
          date: '2025-03 → presente',
          loc: 'Restinga Sêca, RS',
          role: 'Gestão de Indicadores & Automação Digital',
          at: 'Antonio Meneghetti Faculdade',
          status: 'current',
          statusLabel: 'atual',
          modality: 'home-office',
          modalityLabel: 'home office',
          desc: 'Estágio focado em gestão e análise de indicadores institucionais e automação de processos digitais. Atuação com dashboards, workflows automatizados e otimização de fluxos via Pipefy.',
          tags: ['Estágio', 'Automação', 'Pipefy', 'Indicadores'],
        },
        {
          hash: 'jun 2023',
          date: '2023-06 → 2024-12',
          loc: 'Bento Gonçalves, RS',
          role: 'Almoxarife',
          at: 'Auto Pratense',
          status: 'past',
          statusLabel: 'concluído',
          modality: 'presencial',
          modalityLabel: 'presencial',
          desc: 'Responsável pelo controle e gestão do almoxarifado, garantindo o abastecimento adequado de materiais e a integridade do inventário.',
          tags: ['Logística', 'Inventário'],
        },
        {
          hash: 'jun 2018',
          date: '2018-06 → 2020-12',
          loc: 'Itaqui, RS',
          role: 'Menor Aprendiz · Auxiliar de Laboratório',
          at: 'Unipampa — Laboratório de Biologia',
          status: 'past',
          statusLabel: 'concluído',
          modality: 'presencial',
          modalityLabel: 'presencial',
          desc: 'Auxílio em pesquisas científicas e na manutenção do laboratório biológico. Experiência prática com técnicas laboratoriais, protocolos e cuidados com bioterio.',
          tags: ['Pesquisa', 'Biologia', 'Laboratório'],
        },
      ],
    },
    education: {
      cmd: '$ tree ~/educação',
      title: 'formação acadêmica',
      items: [
        {
          name: 'Antonio Meneghetti Faculdade',
          deg: 'Bach. em Sistemas de Informação',
          when: '2025-01 — cursando (2º semestre)',
          note: '★ Participante do CodeRace 2025',
          logo: 'images/LogoAMF.png',
        },
        {
          name: 'I.E.E Osvaldo Cruz',
          deg: 'Ensino Médio',
          when: '2019-01 — 2022-12 · concluído',
          note: null,
          logo: 'images/LogoOsvaldo.jpg',
        },
      ],
    },
    projects: {
      cmd: '$ ls ~/projects/',
      title: 'projetos selecionados',
      items: [
        {
          name: 'ZION',
          version: 'v0.5',
          desc: 'Projeto de inteligência artificial com foco em processamento de linguagem natural e assistência virtual.',
          tags: ['IA', 'Python', 'NLP'],
          status: 'wip',
          statusLabel: 'em desenvolvimento',
          href: 'https://github.com/ViniciusZanonato/ZION',
          img: 'images/LogoZion.png',
          path: '~/projects/zion',
        },
        {
          name: 'NeuroLearn',
          version: 'v1.0',
          desc: 'Plataforma Flask que identifica perfis de aprendizado e indicadores de neurodiversidade via questionários, relatórios gerados por IA (Ollama/Gemini) e analytics comportamental — com dashboards separados para professores e alunos.',
          tags: ['Python', 'Flask', 'IA', 'Ollama'],
          status: 'live',
          statusLabel: 'publicado',
          href: 'https://github.com/ViniciusZanonato/NeuroLearn-Opensource',
          img: 'images/LogoNeuroLearnDark.png',
          path: '~/projects/neurolearn',
        },
        {
          name: 'Enlaçados',
          version: 'v1.0',
          desc: 'Plataforma acadêmica full-stack conectando alunos, professores e instituições — portais por perfil, gestão financeira, relatórios CPA e pagamentos via Stripe.',
          tags: ['React', 'TypeScript', 'Supabase'],
          status: 'live',
          statusLabel: 'publicado',
          href: 'https://github.com/ViniciusZanonato/enlacados-platform',
          img: 'images/enlacados.jpeg',
          path: '~/projects/enlacados',
        },
        {
          name: 'BI Dashboard',
          version: 'v1.0',
          desc: 'Dashboard de BI comercial open-source com multi-setor, RBAC, dados em tempo real, modo TV e push notifications. Integra Pipefy, Make.com, Meta Ads e Google Sheets em uma única interface.',
          tags: ['Next.js', 'TypeScript', 'Supabase', 'Pipefy'],
          status: 'live',
          statusLabel: 'publicado',
          href: 'https://github.com/ViniciusZanonato/bi-dashboard',
          img: 'images/bi-dashboard.png',
          path: '~/projects/bi-dashboard',
        },
      ],
      moreLink: 'ver mais projetos no github',
    },
    courses: {
      cmd: '$ cat ~/cursos.log',
      title: 'cursos & certificações',
      items: [
        { name: 'Bioinformática', org: 'Udemy', topic: 'Análise de sequências genéticas', cat: 'Ciência' },
        { name: 'Microbiologia', org: 'Udemy', topic: 'Técnicas e culturas microbianas', cat: 'Ciência' },
        { name: 'Virologia', org: 'Udemy', topic: 'Ciclo viral e infecções humanas', cat: 'Ciência' },
        { name: 'Engenharia Genética', org: 'Udemy', topic: 'CRISPR e edição de genes', cat: 'Ciência' },
        { name: 'IA para Iniciantes', org: 'Udemy', topic: 'Conceitos, aplicações e ética', cat: 'Tech' },
        { name: 'HTML & CSS', org: 'Antonio Meneghetti Faculdade', topic: 'Desenvolvimento Web', cat: 'Tech' },
        { name: 'Python Básico', org: 'Curso Online', topic: 'Programação', cat: 'Tech' },
        { name: 'Administrador de Sistemas Pipefy', org: 'Pipefy', topic: 'Gerenciar e configurar sistemas', cat: 'Cert', cert: 'images/Certificado_Administrador_de_Sistemas_Pipefy.png' },
        { name: 'Conectando Processos com Pipefy', org: 'Pipefy', topic: 'Automatizar e conectar workflows', cat: 'Cert', cert: 'images/Certificado_Conectando_Processos_com_Pipefy.png' },
        { name: 'CRM de Vendas Pipefy', org: 'Pipefy', topic: 'Gestão e automação de vendas', cat: 'Cert', cert: 'images/Certificado_CRM_de_Vendas_Pipefy.png' },
        { name: 'Expo NovaTech', org: 'Participação', topic: 'Presença e networking', cat: 'Evento', cert: 'images/Certificado_De_Presen_U00e7a_Expo_NovaTech.png' },
        { name: 'Masterclass Interface de Usuário', org: 'Masterclass', topic: 'Princípios de UX/UI', cat: 'Design', cert: 'images/Certificado_Masterclass_Interface_de_Usu_U00e1rio.png' },
      ],
    },
    contact: {
      cmd: '$ mail compose',
      title: 'vamos conversar',
      lead: 'Aberto para oportunidades de estágio, pesquisa, colaborações e papos sobre IA + biociências. Resposta em ~24h.',
      infoTitle: 'canais',
      info: [
        ['email', { type: 'mail', value: 'viniciuszanona@gmail.com' }],
        ['linkedin', { type: 'ext', value: 'Perfil LinkedIn', href: 'https://www.linkedin.com/in/carlos-vinicius-garcia-zanonato-453832346' }],
        ['github', { type: 'ext', value: '@ViniciusZanonato', href: 'https://github.com/ViniciusZanonato' }],
        ['localização', 'Restinga Sêca, RS, Brasil'],
      ],
      form: {
        name: 'nome',
        email: 'email',
        subject: 'assunto',
        message: 'mensagem',
        send: 'enviar mensagem',
        placeholder: {
          name: 'Seu nome',
          email: 'voce@exemplo.com',
          subject: 'Sobre o que vamos falar?',
          message: 'Escreva sua mensagem...',
        },
      },
    },
    footer: {
      built: 'feito à mão · monospace · sem frameworks de UI',
      copy: '© 2025 Carlos Vinicius Garcia Zanonato',
      end: 'EOF',
    },
    tweaks: {
      title: 'Tweaks',
      typography: 'tipografia',
      palette: 'paleta',
      density: 'densidade',
      effects: 'efeitos',
      font: 'fonte',
      grid: 'grade de fundo',
      scanline: 'scanlines',
      densityOpts: { compact: 'compacta', regular: 'regular', comfy: 'ampla' },
    },
  },

  en: {
    locale: 'en-US',
    meta: {
      handle: 'vzanonato',
      host: 'portfolio',
      name1: 'Carlos Vinicius',
      name2: 'Garcia Zanonato',
      role: ['Information Systems', 'Researcher', 'AI & Biosciences'],
      location: 'Restinga Sêca, RS · Brazil',
      status: 'Available',
      timezone: 'BRT (UTC−3)',
    },
    nav: {
      home: 'home',
      about: 'about',
      stack: 'stack',
      experience: 'experience',
      education: 'education',
      projects: 'projects',
      courses: 'courses',
      contact: 'contact',
    },
    hero: {
      cmd: 'whoami',
      cmdOut: 'returned 1 result in 0.003s',
      greeting: 'I’m',
      intro: 'Information Systems student, researcher by nature, passionate about technology, biosciences, and Artificial Intelligence. This space documents my journey — research experience, personal projects, and continuous learning.',
      metaLabels: { based: 'based in', tz: 'timezone', focus: 'focus', langs: 'languages' },
      focus: 'AI · Virology · Genetic Engineering',
      langs: 'PT · EN (intermediate)',
      cta1: 'start a conversation',
      cta2: 'view about.md',
      portraitTag: 'profile.png',
    },
    about: {
      cmd: '$ cat ~/about.md',
      panelLeftFile: 'profile.json',
      panelRightFile: 'summary.md',
      bio: [
        'Information Systems student with 3 years of experience in scientific research and biology lab work at Unipampa. Strong interest in Virology, Genetic Engineering, and Microbiology — areas I’ve deepened through complementary courses.',
        'I aim to integrate technology and biological sciences to build innovative solutions. Currently balancing my IS degree with a passion for research and Artificial Intelligence. Intermediate English, good communication, and motivated by new challenges.',
      ],
      kv: [
        ['name', 'Carlos Vinicius Garcia Zanonato'],
        ['location', 'Restinga Sêca, RS, Brazil'],
        ['email', { type: 'mail', value: 'viniciuszanona@gmail.com' }],
        ['linkedin', { type: 'ext', value: 'carlos-vinicius-garcia-zanonato', href: 'https://www.linkedin.com/in/carlos-vinicius-garcia-zanonato-453832346' }],
        ['github', { type: 'ext', value: '@ViniciusZanonato', href: 'https://github.com/ViniciusZanonato' }],
        ['languages', 'Portuguese (native) · English (intermediate)'],
        ['mei / cnpj', '66.683.588/0001-33'],
      ],
      compHead: 'competencies',
      comps: [
        { v: '3y', l: 'in research' },
        { v: '5+', l: 'projects' },
        { v: '11', l: 'certifications' },
        { v: '∞', l: 'curiosity' },
      ],
    },
    stack: {
      cmd: '$ ls ~/.interests/',
      groupsTitle: 'areas of interest',
      groups: [
        { title: 'technology', items: ['Python', 'JavaScript', 'HTML/CSS', 'AI & LLMs', 'Bioinformatics', 'Pipefy', 'Git'] },
        { title: 'biosciences', items: ['Virology', 'Genetic Engineering', 'Microbiology', 'CRISPR', 'Molecular biology'] },
        { title: 'soft skills', items: ['Research', 'Analytical thinking', 'Communication', 'Fast learning', 'English'] },
      ],
    },
    experience: {
      cmd: '$ git log --oneline experience/',
      title: 'work experience',
      items: [
        {
          hash: 'mar 2025',
          date: '2025-03 → present',
          loc: 'Restinga Sêca, RS',
          role: 'KPIs Management & Digital Automation',
          at: 'Antonio Meneghetti Faculdade',
          status: 'current',
          statusLabel: 'current',
          modality: 'home-office',
          modalityLabel: 'home office',
          desc: 'Internship focused on managing and analyzing institutional KPIs and digital process automation. Working with dashboards, automated workflows, and flow optimization via Pipefy.',
          tags: ['Internship', 'Automation', 'Pipefy', 'KPIs'],
        },
        {
          hash: 'jun 2023',
          date: '2023-06 → 2024-12',
          loc: 'Bento Gonçalves, RS',
          role: 'Warehouse Clerk',
          at: 'Auto Pratense',
          status: 'past',
          statusLabel: 'completed',
          modality: 'on-site',
          modalityLabel: 'on-site',
          desc: 'Responsible for warehouse control and management, ensuring proper material supply and inventory integrity.',
          tags: ['Logistics', 'Inventory'],
        },
        {
          hash: 'jun 2018',
          date: '2018-06 → 2020-12',
          loc: 'Itaqui, RS',
          role: 'Apprentice · Lab Assistant',
          at: 'Unipampa — Biology Lab',
          status: 'past',
          statusLabel: 'completed',
          modality: 'on-site',
          modalityLabel: 'on-site',
          desc: 'Assisted in scientific research and biology lab maintenance. Hands-on experience with lab techniques, protocols, and vivarium care.',
          tags: ['Research', 'Biology', 'Laboratory'],
        },
      ],
    },
    education: {
      cmd: '$ tree ~/education',
      title: 'academic background',
      items: [
        {
          name: 'Antonio Meneghetti Faculdade',
          deg: 'BSc in Information Systems',
          when: '2025-01 — in progress (2nd semester)',
          note: '★ CodeRace 2025 participant',
          logo: 'images/LogoAMF.png',
        },
        {
          name: 'I.E.E Osvaldo Cruz',
          deg: 'High School',
          when: '2019-01 — 2022-12 · completed',
          note: null,
          logo: 'images/LogoOsvaldo.jpg',
        },
      ],
    },
    projects: {
      cmd: '$ ls ~/projects/',
      title: 'selected projects',
      items: [
        {
          name: 'ZION',
          version: 'v0.5',
          desc: 'AI project focused on natural language processing and virtual assistance.',
          tags: ['AI', 'Python', 'NLP'],
          status: 'wip',
          statusLabel: 'in development',
          href: 'https://github.com/ViniciusZanonato/ZION',
          img: 'images/LogoZion.png',
          path: '~/projects/zion',
        },
        {
          name: 'NeuroLearn',
          version: 'v1.0',
          desc: 'Flask platform that identifies learning profiles and neurodiversity indicators via questionnaires, AI-generated reports (Ollama/Gemini) and behavioral analytics — with separate dashboards for teachers and students.',
          tags: ['Python', 'Flask', 'AI', 'Ollama'],
          status: 'live',
          statusLabel: 'published',
          href: 'https://github.com/ViniciusZanonato/NeuroLearn-Opensource',
          img: 'images/LogoNeuroLearnDark.png',
          path: '~/projects/neurolearn',
        },
        {
          name: 'Enlaçados',
          version: 'v1.0',
          desc: 'Full-stack academic platform connecting students, teachers and institutions — role-based portals, financial management, CPA reports and Stripe payments.',
          tags: ['React', 'TypeScript', 'Supabase'],
          status: 'live',
          statusLabel: 'published',
          href: 'https://github.com/ViniciusZanonato/enlacados-platform',
          img: 'images/enlacados.jpeg',
          path: '~/projects/enlacados',
        },
        {
          name: 'BI Dashboard',
          version: 'v1.0',
          desc: 'Open-source commercial BI dashboard with multi-sector views, RBAC auth, real-time data, TV mode and push notifications. Integrates Pipefy, Make.com, Meta Ads and Google Sheets.',
          tags: ['Next.js', 'TypeScript', 'Supabase', 'Pipefy'],
          status: 'live',
          statusLabel: 'published',
          href: 'https://github.com/ViniciusZanonato/bi-dashboard',
          img: 'images/bi-dashboard.png',
          path: '~/projects/bi-dashboard',
        },
      ],
      moreLink: 'see more projects on github',
    },
    courses: {
      cmd: '$ cat ~/courses.log',
      title: 'courses & certifications',
      items: [
        { name: 'Bioinformatics', org: 'Udemy', topic: 'Genetic sequence analysis', cat: 'Science' },
        { name: 'Microbiology', org: 'Udemy', topic: 'Techniques and microbial cultures', cat: 'Science' },
        { name: 'Virology', org: 'Udemy', topic: 'Viral cycle and human infections', cat: 'Science' },
        { name: 'Genetic Engineering', org: 'Udemy', topic: 'CRISPR and gene editing', cat: 'Science' },
        { name: 'AI for Beginners', org: 'Udemy', topic: 'Concepts, applications, ethics', cat: 'Tech' },
        { name: 'HTML & CSS', org: 'Antonio Meneghetti Faculdade', topic: 'Web development', cat: 'Tech' },
        { name: 'Python Basics', org: 'Online', topic: 'Programming', cat: 'Tech' },
        { name: 'Pipefy Systems Admin', org: 'Pipefy', topic: 'Manage and configure systems', cat: 'Cert', cert: 'images/Certificado_Administrador_de_Sistemas_Pipefy.png' },
        { name: 'Connecting Processes with Pipefy', org: 'Pipefy', topic: 'Automate and connect workflows', cat: 'Cert', cert: 'images/Certificado_Conectando_Processos_com_Pipefy.png' },
        { name: 'Pipefy Sales CRM', org: 'Pipefy', topic: 'Sales management and automation', cat: 'Cert', cert: 'images/Certificado_CRM_de_Vendas_Pipefy.png' },
        { name: 'Expo NovaTech', org: 'Attendance', topic: 'Presence and networking', cat: 'Event', cert: 'images/Certificado_De_Presen_U00e7a_Expo_NovaTech.png' },
        { name: 'UI Masterclass', org: 'Masterclass', topic: 'UX/UI principles', cat: 'Design', cert: 'images/Certificado_Masterclass_Interface_de_Usu_U00e1rio.png' },
      ],
    },
    contact: {
      cmd: '$ mail compose',
      title: 'let’s talk',
      lead: 'Open to internships, research, collaborations, and conversations on AI + biosciences. Typical reply in ~24h.',
      infoTitle: 'channels',
      info: [
        ['email', { type: 'mail', value: 'viniciuszanona@gmail.com' }],
        ['linkedin', { type: 'ext', value: 'LinkedIn profile', href: 'https://www.linkedin.com/in/carlos-vinicius-garcia-zanonato-453832346' }],
        ['github', { type: 'ext', value: '@ViniciusZanonato', href: 'https://github.com/ViniciusZanonato' }],
        ['location', 'Restinga Sêca, RS, Brazil'],
      ],
      form: {
        name: 'name',
        email: 'email',
        subject: 'subject',
        message: 'message',
        send: 'send message',
        placeholder: {
          name: 'Your name',
          email: 'you@example.com',
          subject: 'What’s this about?',
          message: 'Write your message...',
        },
      },
    },
    footer: {
      built: 'handcrafted · monospace · no UI frameworks',
      copy: '© 2025 Carlos Vinicius Garcia Zanonato',
      end: 'EOF',
    },
    tweaks: {
      title: 'Tweaks',
      typography: 'typography',
      palette: 'palette',
      density: 'density',
      effects: 'effects',
      font: 'font',
      grid: 'background grid',
      scanline: 'scanlines',
      densityOpts: { compact: 'compact', regular: 'regular', comfy: 'comfy' },
    },
  },
};
